on: [push, pull_request]

name: build

jobs:
  build:
    name: Check package
    uses: r-quantities/workflows/.github/workflows/build.yml@main
    secrets: inherit

  quantities-devel:
    name: Check upstream (devel)
    needs: build
    uses: r-quantities/workflows/.github/workflows/upstream.yml@main
    with:
      version: devel

  quantities-cran:
    name: Check upstream (CRAN)
    needs: build
    uses: r-quantities/workflows/.github/workflows/upstream.yml@main
    with:
      version: cran
